# Generated by Django 4.0.6 on 2022-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION', models.CharField(max_length=100)),
                ('answer', models.IntegerField()),
                ('Option1', models.CharField(max_length=100)),
                ('Option2', models.CharField(max_length=100)),
                ('Optiuon3', models.CharField(max_length=100)),
                ('Option4', models.CharField(max_length=100)),
            ],
        ),
    ]
