# Generated by Django 4.0.6 on 2022-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Option1',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Option2',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Option4',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Optiuon3',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='QUESTION',
        ),
        migrations.AlterField(
            model_name='exam',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='exam',
            table='Exam',
        ),
    ]
